//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPVDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendarevent
    {
        public int idcalendarevent { get; set; }
        public int resourceid { get; set; }
        public System.DateTime begindate { get; set; }
        public System.DateTime enddate { get; set; }
        public int serviceid { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> locked { get; set; }
    
        public virtual resource resource { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
