//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPVDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public long clientId { get; set; }
        public string clientName { get; set; }
        public Nullable<int> numberOfVisits { get; set; }
        public string lastService { get; set; }
        public string lastProduct { get; set; }
        public string contactNumber { get; set; }
        public string clientPicture { get; set; }
    }
}
