//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPVDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tpvenlanubecalendarEntities : DbContext
    {
        public tpvenlanubecalendarEntities()
            : base("name=tpvenlanubecalendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calendarevent> calendarevent { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<resource> resource { get; set; }
        public virtual DbSet<resourcestimeoff> resourcestimeoff { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<shoptimetable> shoptimetable { get; set; }
        public virtual DbSet<shopworkingslices> shopworkingslices { get; set; }
    }
}
