//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPVDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoptimetable
    {
        public shoptimetable()
        {
            this.shopworkingslices = new HashSet<shopworkingslices>();
        }
    
        public int idshoptimetable { get; set; }
        public System.DateTime sliceStart { get; set; }
        public System.DateTime sliceEnd { get; set; }
    
        public virtual ICollection<shopworkingslices> shopworkingslices { get; set; }
    }
}
